name: CMake Multi-Platform Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    # --- CONFIGURAÇÃO LINUX ---
    - name: Install Qt & Deps (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-base-private-dev libgl1-mesa-dev

    # --- CONFIGURAÇÃO WINDOWS ---
    # O Windows-latest já tem o Qt, só precisamos dizer ao CMake onde ele está
    - name: Set Qt Path (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        echo "Qt6_DIR=C:\Qt\6.5.3\msvc2019_64\lib\cmake\Qt6" >> $GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=C:\Qt\6.5.3\msvc2019_64" >> $GITHUB_ENV

    - name: Configure CMake
      # Adicionamos o CMAKE_PREFIX_PATH para garantir que o CMake ache o Qt
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        if [ -f CTestTestfile.cmake ]; then
          ctest -C ${{env.BUILD_TYPE}}
        else
          echo "No tests defined, skipping."
        fi